charts/urls.py
from django.conf.urls import url

import charts.views

urlpatterns = [
    url(r'^$', charts.views.IndexView.as_view(), name='index'),
    url(r'^display/(?P<chart_id>[0-9]+)/$', charts.views.display, name="display"),
    url(r'^dump/(?P<slug_title>[a-z0-9-]+)/$', charts.views.dump, name="dump"),
    url(r'^export/$', charts.views.ExportView.as_view(), name='export'),
    url(r'^import/$', charts.views.import_file, name="import"),
    url(r'^query/(?P<chart_id>[0-9]+)/$', charts.views.query, name="query"),
]

datatoy/urls.py
from django.conf.urls import url
from django.conf.urls import include
from django.contrib import admin

import django.contrib.auth.views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^charts/', include(('charts.urls', 'charts'), namespace='charts')),
    # url(r'^', include('charts.urls', namespace='charts')),
    url(r'^accounts/login/$',
        django.contrib.auth.views.LoginView.as_view(template_name='admin/login.html'),
        name='login'),
]

charts/models.py
from __future__ import unicode_literals

from django.db import models
from django.utils.encoding import python_2_unicode_compatible
from django.utils.text import slugify


@python_2_unicode_compatible
class Chart(models.Model):
    """Models a chart's data."""
    name = models.CharField(max_length=64)
    title = models.CharField(max_length=128)
    slug_title = models.SlugField(max_length=128)
    x_label = models.CharField(max_length=64)
    y_label = models.CharField(max_length=64)

    def save(self):
        """Added to handle slug_title."""
        self.slug_title = slugify(self.title)
        super(Chart, self).save()

    def __str__(self):
        return '%s-%s' % (self.title, self.name)

    class Meta:
        verbose_name_plural = 'Charts'


@python_2_unicode_compatible
class Abscissa(models.Model):
    """Models x axis for a chart. Asserts that x point are inserted in order."""
    x = models.DateField()
    chart = models.ForeignKey(Chart, on_delete=models.CASCADE)

    def __str__(self):
        return '%s-%s-%s' % (self.chart.title, self.chart.name, self.x)

    class Meta:
        verbose_name_plural = 'Chart Abscissa'


@python_2_unicode_compatible
class Data(models.Model):
    """Models y axes of a chart. Asserts that data is inserted in order."""
    column = models.CharField(max_length=64)
    y = models.DecimalField(max_digits=16, decimal_places=4, null=True)
    chart = models.ForeignKey(Chart, on_delete=models.CASCADE)

    def __str__(self):
        if not self.y:
            y_desc = 'missing'
        else:
            y_desc = self.y
        return '%s-%s-%s-%s' % (self.chart.title, self.chart.name, self.column, y_desc)

    class Meta:
        verbose_name_plural = 'Chart Data'

charts/forms.py
from django import forms


class QueryForm(forms.Form):
    """Form for queries on charts displaying."""

    check_all = forms.BooleanField(label="Check All", required=False)

    def __init__(self, y_labels, xs, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.y_labels = y_labels
        for y_label in y_labels:
            self.fields[y_label] = forms.BooleanField(required=False)
        self.fields["from"] = forms.DateField(label="From", required=False, initial=xs[0])
        self.fields["to"] = forms.DateField(label="To", required=False, initial=xs[-1])
        self.start_date = xs[0]
        self.end_date = xs[-1]
        self.fields["operation"] = forms.ChoiceField(choices=(('ORIG', 'raw data'),
                                                              ('PERCENT', 'percentage'),
                                                              ('VAR', 'growth rate'),
                                                              ))
        self.fields["chart_style"] = forms.ChoiceField(choices=(('LINES', 'lines'),
                                                                ('DOTS', 'dots'),
                                                                ('LINE_DOTS', 'lines with dots'),
                                                                ('LINES_LEGEND', 'lines with legend'),
                                                                ))
        self.fields["tool"] = forms.ChoiceField(choices=(('NONE', '--'),
                                                         ('SMA', 'moving average'),
                                                         ('LR', 'logistic fit'),
                                                         ('DAY0', 'day 0 prediction')))
        self.fields["window_size"] = forms.ChoiceField(choices=((3, '3'), (4, '4'), (5, '5'),
                                                                (7, '7'), (14, '14')))
        self.fields["log_y"] = forms.BooleanField(label="Log y", required=False)

    def clean_from(self):
        """'from' date validator."""
        from_ = self.cleaned_data["from"]
        if from_ < self.start_date:
            raise forms.ValidationError("Date cannot be less than %s" % self.start_date)
        return from_

    def clean_to(self):
        """'to' date validator."""
        to = self.cleaned_data["to"]
        if to > self.end_date:
            raise forms.ValidationError("Date cannot be more than %s" % self.end_date)
        return to

    def clean(self):
        """For now validates that at least one checkbox is checked."""
        cleaned_data = super(QueryForm, self).clean()
        for y_label in self.y_labels:
            if cleaned_data[y_label]:
                return None
        raise forms.ValidationError("At least one checkbox must be checked")


class ImportForm(forms.Form):
    """Form for importing data into model."""
    import_filename = forms.FileField(label='Data File')
    sheet_name = forms.CharField(label='Excel Data Sheet', required=False)
    y_label = forms.CharField(label='Unit of y axes', required=False)
    period = forms.ChoiceField(choices=(('D', 'date'), ('Y', 'year')))
    transformation = forms.ChoiceField(choices=(('TABULAR', 'tabular'), ('GROUPBY', 'groupby')))
    group_by_col_name = forms.CharField(label='Group aggregation column name', required=False)
    summary_col_name = forms.CharField(label='Groups summary column names space separated',
                                       required=False)

charts/views.py
"""Django Views for charts application."""

from __future__ import unicode_literals

from bokeh.embed import components
from bokeh.resources import CDN
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.utils.text import slugify
from django.views import generic

import charts.adapters.adapter_factory as adapter_factory
import charts.presenters.export_presenters as export_presenters
import charts.presenters.ui_presenter_factory as presenter_factory
import charts.repositories.model_repository as model_repo
import charts.usecases.chart_usecases as usecases
import charts.usecases.usecase_factory as usecases_factory
from charts.forms import ImportForm
from charts.forms import QueryForm
from charts.models import Chart
from charts.repositories.repository_factory import create_read_repository


class IndexView(generic.ListView):
    """Generic view for charts."""
    model = Chart
    template_name = 'charts/index.html'
    context_object_name = 'charts'


class ExportView(generic.ListView):
    """Generic view for charts reports."""
    model = Chart
    template_name = 'charts/export.html'
    context_object_name = 'charts'


def query(request, chart_id):
    """Main View for filtering by columns.
    :param request: http request
    :param chart_id: id pk
    :return http response
    """
    repo = model_repo.ChartRepository(chart_id)
    chart = repo.read()
    form = QueryForm(chart.y_labels, chart.xs)
    return render(request, "charts/query.html", {"form": form, "chart": chart})


def display(request, chart_id):
    """Displays a chart from query form.
    :param request: http request
    :param chart_id: id pk
    :return http response
    """
    if request.method == 'POST':
        repo = model_repo.ChartRepository(chart_id)
        chart = repo.read()
        form = QueryForm(chart.y_labels, chart.xs, request.POST)
        if form.is_valid():
            if form.cleaned_data['tool'] != 'NONE':
                tool_params = {'window_size': (form.cleaned_data['window_size'])}
                adapter = adapter_factory.create_adapter(form.cleaned_data['tool'], **tool_params)
            else:
                adapter = None
            y_labels = [y for y in chart.y_labels if form.cleaned_data[y]]
            from_date = form.cleaned_data['from']
            to_date = form.cleaned_data['to']
            uc_selection = form.cleaned_data['operation']
            uc = usecases_factory.create_usecase(uc_selection, chart, adapter)
            uc.filter(y_labels, from_date, to_date)
            chart_style = form.cleaned_data['chart_style']
            is_log_y = form.cleaned_data['log_y']
            response = uc.execute()
            p = presenter_factory.create_presenter(chart_style, response, is_log_y)
            chart = p.get_displayable_object()
            script, div = components(chart, CDN)
            return render(request, "charts/chart.html",
                          {"script": script, "div": div,
                           "chart_title": uc.title})
        return render(request, "charts/query.html", {"form": form, "chart": chart})


@login_required()
def import_file(request):
    """Upload a chart from excel, every sheet is a chart.
    A sheet is assumed to be like a data frame: the first column is
    the x axis, other columns are y axis, the first row contains the
    field names.
    Supports also csv files with group by aggregation.
    :param request: http request
    :return http response
    """
    if request.method == 'POST':
        form = ImportForm(request.POST, request.FILES)
        if form.is_valid():
            import_file_obj = request.FILES['import_filename']
            chart_name = form.cleaned_data['sheet_name']
            repo = create_read_repository(import_file_obj, chart_name,
                                          form.cleaned_data['y_label'],
                                          form.cleaned_data['period'])
            selected_transformation = form.cleaned_data['transformation']
            group_by_col_name = form.cleaned_data['group_by_col_name']
            summary_col_name = form.cleaned_data['summary_col_name']
            import_usecase = usecases_factory.create_import_usecase(selected_transformation,
                                                                    repo.read(),
                                                                    group_by_col_name,
                                                                    summary_col_name)
            for entity in import_usecase.execute():
                model_repo.ChartRepository.write(entity)
            return HttpResponseRedirect('/charts')
    else:
        form = ImportForm()
    return render(request, 'charts/import.html', {'form': form})


@login_required()
def dump(request, slug_title):
    """Returns xls file reconstructed from db.
    :param request: http request
    :param slug_title: str
    :return http response
    """
    response = HttpResponse(content_type='application/vnd.ms-excel')
    repository = model_repo.ChartSetRepository(slug_title)
    use_case = usecases.ChartSetUseCase(repository.read())
    response_set = use_case.get_data_responses()
    response['Content-Disposition'] = 'attachment; filename=%s.xls' % slugify(response_set[0]['title'])
    presenter = export_presenters.DataBookPresenter(response_set)
    data_book = presenter.get_data_book()
    response.write(export_presenters.data_book_to_xls_stream(data_book))
    return response

charts/templates/charts/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}Data Toy{% endblock %}</title>

    {% load staticfiles %}

    <!-- Bootstrap -->
    <link rel="stylesheet" type="text/css" href="{% static 'charts/css/bootstrap.min.css' %}"/>
    <!-- Bootstrap theme -->
    <link rel="stylesheet" type="text/css" href="{% static 'charts/css/bootstrap-theme.min.css' %}"/>

    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <link rel="stylesheet" type="text/css" href="{% static 'charts/css/ie10-viewport-bug-workaround.css' %}"/>

    <link rel="stylesheet" type="text/css" href="{% static 'charts/css/style.css' %}"/>

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->

    {% block extra_head %}
    {% endblock %}

</head>
<body>

<nav class="navbar navbar-inverse navbar-fixed-top">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar"
                    aria-expanded="false" aria-controls="navbar">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="/charts">Data Toy</a>
        </div>
        <div id="navbar" class="collapse navbar-collapse">
            <ul class="nav navbar-nav">
                <li class="active"><a href="/charts">Home</a></li>
                <li><a href="/admin">Admin</a></li>
                <li><a href="/charts/import">Import</a></li>
                <li><a href="/charts/export">Export</a></li>
            </ul>
        </div><!--/.nav-collapse -->
    </div>
</nav>

<div class="container" role="main">

    <div class="starter-template">

        {% block body %}
        {% endblock %}

    </div>

</div>

<!-- Bootstrap core JavaScript
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
<script>window.jQuery || document.write('<script src="../../assets/js/vendor/jquery.min.js"><\/script>')</script>
<script src="{% static 'charts/js/bootstrap.min.js' %}"></script>
<!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
<script src="{% static 'charts/js/ie10-viewport-bug-workaround.js' %}"></script>

{% block extra_js %}
{% endblock %}

</body>
</html>

charts/templates/charts/chart.html
{% extends 'charts/base.html' %}

{% block title %}{{ chart_title }}{% endblock %}
{% block extra_head %}
    <script src="https://cdn.bokeh.org/bokeh/release/bokeh-2.0.2.js"></script>
    <!--
    <script src="https://cdn.bokeh.org/bokeh/release/bokeh-widgets-2.0.2.min.js"></script>
    <script src="https://cdn.bokeh.org/bokeh/release/bokeh-tables-2.0.2.min.js"></script>
    <script src="https://cdn.bokeh.org/bokeh/release/bokeh-api-2.0.2.min.js"></script>
    -->
    <script type="text/javascript">
        Bokeh.set_log_level("info");
    </script>
{% endblock %}

{% block body %}
    {{ div|safe }}
    {{ script|safe }}
{% endblock %}

charts/templates/charts/export.html
{% extends 'charts/base.html' %}

{% block body %}
    <h1>Export data sets to Excel</h1>
    <div class="form-group">
        <input placeholder="Search" id="search" type="text" class="form-control"/>
    </div>
    {% if charts %}
        {% regroup charts|dictsort:"title" by title as chart_list %}
        <div id="nested-list">
            <ul class="navList">
                {% for chart_title in chart_list %}
                    <li>
                        <a href="{% url 'charts:dump' chart_title.list.0.slug_title %}">{{ chart_title.grouper }}</a>
                    </li>
                    <li>
                        <ul>
                            {% for chart in chart_title.list %}
                                <li>{{ chart.name }}</li>
                            {% endfor %}
                        </ul>
                    </li>
                {% endfor %}
            </ul>
        </div>
    {% else %}
        <p>No data sets are available.</p>
    {% endif %}
{% endblock %}

{% block extra_js %}
    {% load staticfiles %}
    <script src="{% static 'charts/js/search.js' %}"></script>
{% endblock %}

charts/templates/charts/import.html
{% extends 'charts/base.html' %}

{% block title %}Import{% endblock %}

{% block body %}
    <h1>Import data sets from Excel or Csv</h1>
    <div id="id_import_form">
        <form enctype="multipart/form-data" action="{% url 'charts:import' %}" method="post">
            {% csrf_token %}
            <div class="row">
                <div class="col-md-6">
                    <table class="table" width="400" cellpadding="30">
                        {{ form.as_table }}
                    </table>
                </div>
            </div>
            <p><input type="submit" value="Submit" class="btn btn-success"/></p>
        </form>
    </div>
{% endblock %}>

charts/templates/charts/index.html
{% extends 'charts/base.html' %}

{% block body %}
    <div class="jumbotron">
        <h1>Data Toy</h1>
        <p>A Data visualizations Toy project.</p>
    </div>
    <div class="form-group">
        <input placeholder="Search" id="search" type="text" class="form-control"/>
    </div>
    {% if charts %}
        {% regroup charts|dictsort:"title" by title as chart_list %}
        <div id="nested-list">
            <ul class="navList">
                {% for chart_title in chart_list %}
                    <li>
                        {{ chart_title.grouper }}
                        <ul>
                            {% for chart in chart_title.list %}
                                <li><a href="{% url 'charts:query' chart.id %}">{{ chart.name }}</a></li>
                            {% endfor %}
                        </ul>
                    </li>
                {% endfor %}
            </ul>
        </div>
    {% else %}
        <p>No charts are available.</p>
    {% endif %}
{% endblock %}

{% block extra_js %}
    {% load staticfiles %}
    <script src="{% static 'charts/js/search.js' %}"></script>
{% endblock %}

charts/templates/charts/query.html
{% extends 'charts/base.html' %}

{% block title %} {{ chart.title }} {% endblock %}

{% block extra_head %}
    <link rel="stylesheet" href="https://ajax.googleapis.com/ajax/libs/jqueryui/1.11.3/themes/smoothness/jquery-ui.css">
{% endblock %}

{% block body %}
    <h1>Available Data</h1>
    <form action="{% url 'charts:display' chart.id %}" method="post">
        {% csrf_token %}
        <table width="150">
            {{ form.as_table }}
        </table>
        <p><input type="submit" value="Submit" class="btn btn-success"/></p>
    </form>
{% endblock %}

{% block extra_js %}
    {% load staticfiles %}
    <script src="{% static 'charts/js/check-all-checkbox.js' %}"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.11.3/jquery-ui.min.js"></script>
    <script src="{% static 'charts/js/datepickers.js' %}"></script>
{% endblock %}